#ifndef BLOCKTYPE_H
#define BLOCKTYPE_H

enum BlockType {RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, REGMATCHED, SPECMATCHED, EMPTY, DEAD,
                REDMATCHED, GREENMATCHED, BLUEMATCHED, YELLOWMATCHED, ORANGEMATCHED, PURPLEMATCHED };

#endif // BLOCKTYPE_H
